### ISSUE TITLE
Missing Redis support for Rack

### ISSUE THREAD

**Issue by milesmatthias** [redis-store/redis-rack#12]
I followed the instructions in the [redis-rails' readme](https://github.com/redis-store/redis-rails/blob/master/README.md) to do something like this:

```ruby
# config/environments/production.rb
config.action_dispatch.rack_cache = {
  metastore:   'redis://localhost:6379/1/metastore',
  entitystore: 'redis://localhost:6379/1/entitystore'
}
```

however every rack cache is a pass. Debugging a bit, I found that anytime rack tries to instantiate the store (redis in our case), it won't because it doesn't seem like one of the store types they support. This error is thrown for me: https://github.com/rtomayko/rack-cache/blob/129dc7ab063c1ce9b4cfd5eb77fbd7fe36ba2aca/lib/rack/cache/storage.rb#L50

And even with `redis-rails` in my Gemfile and installed, the list of supported store types for Rack looks like this:

```
=> [:Heap,
 :HEAP,
 :MEM,
 :Disk,
 :DISK,
 :FILE,
 :MemCacheBase,
 :Dalli,
 :MemCached,
 :MEMCACHE,
 :MEMCACHED,
 :GAEStore,
 :GAECACHE,
 :GAE,
 :RAILS]
```

`:RAILS` isn't one of the type constants listed in rack-cache, so I'm guessing that's what the `redis-rack` gem added, but obviously it should be `:REDIS` instead of `:RAILS` or the configuration option should be `rails://127...` but the latter is confusing to the end user.

I'm trying to find where this constant is added so I can fix it. Any guidance here would be appreciated.

**Comment by milesmatthias** [comment]
Any advice on this @shiro16 or @radar?

**Comment by tubbo** [comment]
Do you also have rack-cache and redis-rack-cache in your Gemfile?

**Comment by milesmatthias** [comment]
I have

```
gem 'rack-cache'
gem 'redis-rails'
```

which in my `Gemfile.lock` includes `redis-rack`.

Is `redis-rack` not the same as `redis-rack-cache`? The README must need updating if not.

**Comment by tubbo** [comment]
No, it's not. I don't believe `redis-rack` was the most descriptive name for this gem, as it's actually meant to use Redis as a store for the Rack session, similar to how you can use Redis as a store for the Rails session (which, I believe, is built on top of Rack as well). You do need redis-rack-cache in the Gemfile, because redis-rack-cache relies on rack-cache, and rack-cache is not a bundled component of Rails. We don't want redis-rails to be coupled to rack-cache, because some apps use HTTP-level caches (such as Varnish or Squid proxy) instead of the less feature-rich Rack::Cache.

Try adding redis-rack-cache, I know I have to add it on every project...

**Comment by milesmatthias** [comment]
Thanks @tubbo, that does in fact fix my issue. I'll submit a PR for the README on the `redis-rails` gem then, because this was extremely confusing with an extremely easy fix.

**Comment by tubbo** [comment]
Thanks so much!

On 01/06, Miles Matthias wrote:
> Thanks @tubbo, that does in fact fix my issue. I'll submit a PR for the README on the `redis-rails` gem then, because this was extremely confusing with an extremely easy fix.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/redis-store/redis-rack/issues/12#issuecomment-169424797

-- 
- T
