### ISSUE TITLE
Issue with rack session in sinatra

### ISSUE THREAD

**Issue by matthewford** [redis-store/redis-rack#67]
```
Unexpected error while processing request: undefined method `private_id' for #<String:0x0000557f81ac6150>
 Did you mean?  private_methods
/usr/local/bundle/gems/redis-rack-2.1.3/lib/rack/session/redis.rb:49:in `block (2 levels) in write_session'
```

rack (2.2.3), redis-rack 2.1.3, redis-store 1.9.0, sinatra 2.1.0

Any ideas why that method is failing?

**Comment by tubbo** [comment]
This usually happens when you migrate to a newer version of Rack, which changed the Session API to include both private and public IDs. The data in your Redis DB is still using String IDs, but the code is written to support `Rack::Session::ID`. Clearing out your sessions in Redis should resolve the issue, since new writes will be in the correct format.
